# Proxy /rapt-auth locally to RAPT's identity server
[[redirects]]
  from = "/rapt-auth"
  to = "https://id.rapt.io/connect/token"
  status = 200
  force = true

# Proxy /rapt-api locally to RAPT's data API
[[redirects]]
  from = "/rapt-api/*"
  to = "https://api.rapt.io/api/:splat"
  status = 200
  force = true

# Handle React Router (SPA Fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
